// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1oLhUEPxklEHVv0NxcRuHZrQ8tEH1CY',
    appId: '1:7284030244:android:b597b6778c0e67c847d1b1',
    messagingSenderId: '7284030244',
    projectId: 'sleep-tracker-13aa5',
    databaseURL: 'https://sleep-tracker-13aa5-default-rtdb.firebaseio.com',
    storageBucket: 'sleep-tracker-13aa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnFhxNsacMSlDXxwPykcvC0n5_TMguTv0',
    appId: '1:7284030244:ios:02b1a63b6d2743c247d1b1',
    messagingSenderId: '7284030244',
    projectId: 'sleep-tracker-13aa5',
    databaseURL: 'https://sleep-tracker-13aa5-default-rtdb.firebaseio.com',
    storageBucket: 'sleep-tracker-13aa5.appspot.com',
    iosClientId: '7284030244-9git4v6kq4qv1riksjddicmef62n2luh.apps.googleusercontent.com',
    iosBundleId: 'com.example.theresaTest',
  );
}
